create user CRAMER_INSTALLER identified by CRAMER_INSTALLER;
grant	
	CREATE SESSION,
	CREATE TYPE,
	CREATE TABLE,
	CREATE TRIGGER,
	CREATE SEQUENCE,
	CREATE INDEXTYPE,
	CREATE PROCEDURE,
	CREATE VIEW,
	AQ_ADMINISTRATOR_ROLE,
	SELECT ANY DICTIONARY
to CRAMER_INSTALLER with admin option;



GRANT JAVA_ADMIN TO CRAMER_INSTALLER;
GRANT CREATE USER TO CRAMER_INSTALLER;

CREATE SYNONYM CRAMER_INSTALLER V_$SESSION FOR V_$SESSION;
CREATE SYNONYM CRAMER_INSTALLER V_$PARAMETER FOR V_$PARAMETER;
CREATE SYNONYM CRAMER_INSTALLER V_$INSTANCE FOR V_$INSTANCE;

GRANT analyze any to CRAMER_INSTALLER;
GRANT EXECUTE ON DBMS_LOCK TO CRAMER_INSTALLER;
GRANT EXECUTE ON DBMS_PIPE TO CRAMER_INSTALLER;
GRANT EXECUTE ON DBMS_RLS TO CRAMER_INSTALLER;
GRANT EXECUTE ON dbms_job TO CRAMER_INSTALLER WITH GRANT OPTION;

GRANT EXECUTE ON UTL_FILE TO CRAMER_INSTALLER;

grant create public synonym to  CRAMER_INSTALLER;

grant create role to  CRAMER_INSTALLER;
grant drop ANY role to  CRAMER_INSTALLER;
GRANT ALTER DATABASE to CRAMER_INSTALLER;
grant create any directory to  CRAMER_INSTALLER;

grant execute on xmldom 	to  CRAMER_INSTALLER;
grant execute on xmlparser 	to  CRAMER_INSTALLER;
grant create any context to  CRAMER_INSTALLER;
grant execute any type to  CRAMER_INSTALLER with admin option;
GRANT EXECUTE ON DBMS_AQADM TO  CRAMER_INSTALLER WITH GRANT OPTION;
GRANT EXECUTE ON DBMS_AQ TO  CRAMER_INSTALLER WITH GRANT OPTION;
grant execute on DBMS_CRYPTO to CRAMER_INSTALLER;
grant execute on DBMS_RESULT_CACHE to CRAMER_INSTALLER;
